### ISSUE TITLE
[Bug] Cause AE2 Pattern Access Terminal UI Texts Disappear

### ISSUE THREAD

**Issue by StarskyXIII** [BloCamLimb/ModernUI#117]
**Describe the bug**
When enable Modern Text Engine, Texts of Pattern Access Terminal will not display.

**To Reproduce**
1. Place a Pattern Provider in the wolrd, and connect it to ME Network
2. Place a Pattern Access Terminal in the ME Network
3. Open the Pattern Access Terminal GUI

**Expected behavior**
Display name of block which adjacent Pattern Provider.

**Screenshots**
Enabled Modern Text Engine
![image](https://user-images.githubusercontent.com/71606873/179913468-a621c908-8ae6-4e49-92c3-9c69069107dc.png)

Disabled Modern Text Engine
![image](https://user-images.githubusercontent.com/71606873/179913495-5374d547-fd61-4133-af2b-3af240b2c31f.png)

**Environment**
 - Mod Version: Applied Energistics2 v11.1.4, Modern UI v3.5.0.109
 - Forge Version: 40.1.68
 - Operating System: Windows 11
 - Graphics Card: EVGA GeForce RTX 3060 XC GAMING
 - Other Mods:

Maybe similar problem https://github.com/the9grounds/AE-Additions/issues/84

**Comment by BloCamLimb** [comment]
AE2 may set alpha to 1, so it's nearly transparent. Alpha value should be set to 0 (considered as 0xRRGGBB format and alpha will be adjusted to 255) or directly to 255 (fully opaque). Somehow the alpha threshold used by Minecraft Vanilla is 4, so `0 <= alpha < 4` will be adjusted to 255, but Modern UI won't handle this. Because it doesn't make sense, If you make an alpha animation, you can't explain the value of a small alpha.

**Comment by StarskyXIII** [comment]
It seems not be fixed in latest version.
I also deleted the old config files.
![image](https://user-images.githubusercontent.com/71606873/179964708-93e7efc1-7648-41f0-943d-2297feab8f06.png)

**Comment by BloCamLimb** [comment]
I got that, it's caused by fast path.
