### ISSUE TITLE
[Bug?] 文本布局 默认字体行为选择”保留全部“或者”保留ASCII"时空格宽度被压缩

### ISSUE THREAD

**Issue by drag0n1zed** [BloCamLimb/ModernUI#204]
**Describe the bug**
如题

**To Reproduce**
1. 纯净1.18.2 Forge环境安装Modern UI
2. Ctrl+K中启用文本渲染引擎，文本布局-默认行为选择“保留全部”或者“保留ASCII”

**Expected behavior**
空格宽点

**Screenshots**
![2024-02-12_23 29 37](https://github.com/BloCamLimb/ModernUI/assets/62168687/f895b397-9417-43b5-86a3-468040b24e6b)

**Environment**
 - Mod Version: 3.10.0.1
 - Forge Version: 40.2.17
 - Operating System: Windows 11 23H2
 - Graphics Card: RTX 4070
 - Other Mods: None

**Comment by BloCamLimb** [comment]
This is the expected behavior.
Minecraft introduced SpaceFont in 1.19, which is used to handle space characters in vanilla text system. It's KEEP ALL in 1.19+, then Minecraft default font is used for ASCII characters. If you set it to KEEP ALL in 1.18, the space character will be too narrow, so it's KEEP OTHER by default.

这就是预期行为。
Minecraft在1.19添加空格字体，用于处理原版文字系统的空格字符，所以1.19以上是保留全部。如果你在1.18设成保留全部，由于无法使用原版的宽空格，所以它会很窄，这就是1.18默认是保留其他的原因。1.18只是1.20的向后迁移版本，不能保证所有东西都完美运作。
