### ISSUE TITLE
incompatibility with Text Utilities

### ISSUE THREAD

**Issue by peow** [BloCamLimb/ModernUI#209]
Text Utilities (https://modrinth.com/mod/text-utilities) allows you to easily decide which color you want to use in the texts, and whether they should be in Bold, Italic, etc.
![image](https://github.com/BloCamLimb/ModernUI/assets/105888751/08277b2d-68f6-4a6a-adff-480f5c5a007b)

however, when used together with Modern UI, the color menu is bugged

**without** ModernUI
![2024-03-24_10 52 39](https://github.com/BloCamLimb/ModernUI/assets/105888751/1c6dc1a4-6a74-4b80-82d6-b2db9e40c90f)
-----------

**with** ModernUI
![2024-03-24_10 53 46](https://github.com/BloCamLimb/ModernUI/assets/105888751/c18a45a8-cdcb-4387-96b2-38ba9df10849)

this stop happening when you disable "Modern Text Engine"
![image](https://github.com/BloCamLimb/ModernUI/assets/105888751/f554cb72-031d-49cf-9bdb-dcf0510b567a)

if it is possible to fix this, please publish an update for fabric 1.20.1

**Comment by BloCamLimb** [comment]
I didn't see anything wrong.
The color button has the character U+2B1B '⬛' which is an emoji character (and default to emoji style), then it's rendered as an color emoji using Google Noto Color Emoji. If you want it to render to text style, you can disable Color Emoji, or append U+FE0E 'VS-15' character. '⬛︎'
The bold style for Minecraft bitmap fonts is deprecated by Modern Text Engine, due to its low performance and bad looking. You could, alternatively, select a TrueType/OpenType font and abandon those bitmap fonts.

**Comment by BloCamLimb** [comment]
This is because the tooltip mod you are using assumes that the space has a fixed width of 4. But the width of space varies in different fonts. In your case, space becomes narrower, so more spaces are needed to provide sufficient indentation. You can take a look at this issue and report it to the tooltip mod author
https://github.com/wisp-forest/numismatic-overhaul/issues/108#issuecomment-1840734175

**Comment by Shodelat** [comment]
> disabling Color Emoji solved the color issue I'm trying to find a font that suits Minecraft but I'm having trouble, most are too soft for a cubic game, I'm trying to find a free font that can be used in a modpack

you could just use original font or font from any resource pack. faithful for example

**Comment by Shodelat** [comment]
> the original font doesnt work well with ModernUI

hmm I have no problems with it, could you please describe your needs of non-original font? what makes you want other?

**Comment by Shodelat** [comment]
> the original Minecraft font doesn't accept **bold** when using ModernUI

oh I get it, thanks for fast reply
