### ISSUE TITLE
[Developing Bug] Missing Maven Repository in `common:build.gradle`

### ISSUE THREAD

**Issue by xia-mc** [BloCamLimb/ModernUI#248]
**Describe the bug**  
The `common:build.gradle` file in the Modern UI project is missing a necessary Maven repository. This causes the build process to fail in environments without cached dependencies. 
Specifically, the repository for `IzzelAliz Maven` is missing, which is required to resolve certain dependencies during the build.

**To Reproduce**  
1. Clone the Modern UI repository.
2. Clear your Maven cache or use a clean environment without cached dependencies.
3. Try to build the project using Gradle.
4. The build will fail due to missing dependencies.

**Expected behavior**  
The project should successfully build even in environments without cached dependencies. Adding the following repository to the `repositories` block in `common:build.gradle` resolves the issue:

```groovy
maven {
    name 'IzzelAliz Maven'
    url 'https://maven.izzel.io/releases/'
}
```

**Environment**  
- Mod Version: N/A
- Forge Version: N/A
- Operating System: Any
- Graphics Card: N/A
- Other Mods: N/A

**Comment by BloCamLimb** [comment]
It seems that you are referring to the ModernUI-MC repository rather than ModernUI. We commonly use Composite Build for ModernUI-MC, which requires cloning these two repositories. The backup plan you used is almost obsolete, because the latest commit of ModernUI-MC may not necessarily be built on the stable release of ModernUI, which may cause compilation errors.

**Comment by BloCamLimb** [comment]
https://github.com/BloCamLimb/ModernUI-MC/commit/60fdb7772bb4f2e1cc0c7816851918e8f274ec88
