### ISSUE TITLE
[Bug] Inline (mod) compatibility/Mixin override causes incompatibilities

### ISSUE THREAD

**Issue by FunnyBunny14** [BloCamLimb/ModernUI#251]
Incompatible with Inline due to mixin override, causes crash and doesn't start up
https://github.com/SamsTheNerd/inline/issues/9

Install inline, install modernui, launch the game. 

The mixins should both be able to apply? Or at least not crash the game.

Minecraft 1.20.1
 - Mod Version: most recent
 - Forge Version: neoforge, most recent

**Comment by BloCamLimb** [comment]
There is no way to be compatible with it, the only solution is to disable Modern Text Engine.

Because Modern Text Engine processes and renders text not on a per codepoint basis, but on a per grapheme cluster or glyph basis, in favor of internationalization support. All vanilla methods that use codepoints have been abandoned (and overwritten by Modern Text Engine).

Open `/.minecraft/config/ModernUI/bootstrap.properties`, add line `modernui_mc_disableTextEngine=true`, save as UTF-8 encoding.

If you are a mod developer, you can join my Discord for technical support.

**Comment by FunnyBunny14** [comment]
Ah, so then we could use caxton to render text stuff instead! Okay, thank you very much! We now have modern ui, with good text fonts, and hex casting!

**Comment by BloCamLimb** [comment]
Caxton is also not compatible with Inline, it just won't crash the game, Inline will not function.
