### ISSUE TITLE
[Bug] Fragment 显示后未触发 onResume() 生命周期方法

### ISSUE THREAD

**Issue by LovelyCane** [BloCamLimb/ModernUI#252]
**Describe the bug**
根据代码注释并参考 Android 开发文档中关于生命周期的说明，当一个 Fragment 被显示时，其生命周期方法 onResume() 应被调用。然而，在实际模组开发中，Fragment 的 onResume() 方法未被触发。

**To Reproduce**
1. 创建一个新的 Fragment 并重写其 onResume() 方法，例如添加日志或其他自定义逻辑
2. 使用 MuiModApi 提供的 openScreen 方法打开该 Fragment

**Expected behavior**
当 Fragment 被显示后，控制台应输出 onResume() 方法中的日志

**Screenshots**
![PixPin_2024-11-19_19-25-46](https://github.com/user-attachments/assets/97f11637-ecdf-411d-aa72-9e436efc4505)

**Environment**
 - Mod Version: 3.11.0.1
 - Fabric Version: 0.92.2+1.20.1
 - Operating System: Windows 11
 - Graphics Card: NVIDIA GeForce GTX 1060 3GB
 - Other Mods: jei lazydfu mousetweaks noisium porting_lib reach-entity-attributes rrls skinlayers3d sodium starlight

**Comment by BloCamLimb** [comment]
True, this would be fixed in 3.11.1.

But now the lifecycle in ModernUI is still not working as expected, that is, onPause() will not be called when the window focus is lost, and onStop() will not be called when the window is minimized, they are just called when the fragment is destroyed. This will be completed in the future releases.
