### ISSUE TITLE
[1.16.5][Bug] Crashing when loading world.

### ISSUE THREAD

**Issue by dreckz** [BloCamLimb/ModernUI#73]
**Describe the bug**
Was playing in a singleplayer world and the world ended up crashing on me.  My crash log said it was related to ModernUI.  Upon taking out ModernUI from the modlist, the game no longer suffered from worldgen lag as well.  This lag also was on startup too, approx 20 sec for world to load.

**To Reproduce**
1. Attempt to load new chunks in modpack

**Expected behavior**
The chunks are supposed to load normally

**Screenshots**
Crashlog:
[crash-2021-08-29_18.43.26-client.txt](https://github.com/BloCamLimb/ModernUI/files/7073391/crash-2021-08-29_18.43.26-client.txt)
Sparkc report of lag occuring beforehand:
https://spark.lucko.me/oEqy6woScH?hl=15,24,37

**Environment**
 - Mod Version: 2.5.1.86
 - Forge Version: 36.2.0
 - Operating System: WIN 10
 - Graphics Card: RTX 2070 Super
 - Other Mods: See Crashlog

**Comment by BloCamLimb** [comment]
https://github.com/BloCamLimb/ModernUI/commit/d1b6d4a122df4ba1beb64a321fd644fc2427f9cc https://github.com/BloCamLimb/ModernUI/commit/506e2afaeab1dcc7b8e80fa6ed6eee777f75b442 https://github.com/BloCamLimb/ModernUI/commit/5f44656cf222d0b83450ea51d06e89c64c28bdeb
This should be fixed in new text engine.
