### ISSUE TITLE
[Question] Disabling blur effect with some item

### ISSUE THREAD

**Issue by didis54** [BloCamLimb/ModernUI#8]
**Describe the bug**
Is it possible to deactivate the Blur for some item added by other mods ?
With Structurize for example

**To Reproduce**
Structurize Building, Scan and Shape tool

**Versions you are on**
 - Mod Version: 1.5.8.55
 - Forge Version: 31.2.0

**Comment by BloCamLimb** [comment]
Do you mean disable blur effect in those items' GUI?

**Comment by didis54** [comment]
Yes exactly

**Comment by BloCamLimb** [comment]
I can offer a long-term method in next version, that needs you to manually have gui blacklisted. Because this may be determined by the preferences of the players. You will have to enable developer mode to print open gui class name to log file, and put the name into config. But the next version will be a big update, so it will take a while.

**Comment by BloCamLimb** [comment]
New version released, modify `blurGuiExclusions` in `\.minecraft\config\ModernUI\client.toml` to `["com.ldtteam.structurize.client.gui.AbstractWindowSkeleton"]`, this should work for all Structurize guis.
